tasks:
  - init: |
      docker rm -f streamlit-rag-alex-frontend-1 streamlit-rag-alex-backend-1 || true
      docker network prune -f || true
  - command: docker-compose up --build

ports:
  - port: 8501
    onOpen: open-preview
    description: Streamlit Frontend
  - port: 8000
    onOpen: open-preview
    description: FastAPI Backend

vscode:
  extensions:
    - ms-python.python
    - ms-python.flake8
    - ms-python.black-formatter
    - ms-vscode.vscode-json
    - ms-vscode.vscode-yaml
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
