services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REBRICKABLE_API_KEY=${REBRICKABLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REBRICKABLE_BASE_URL=${REBRICKABLE_BASE_URL:-https://rebrickable.com/api/v3/lego/}
      - PORT=8000

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - REBRICKABLE_API_KEY=${REBRICKABLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
